apiVersion: batch/v1
kind: Job
metadata:
  name: dnsresolver
  namespace: kube-system
spec:
#  successfulJobsHistoryLimit: 0
  ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
        - name: dnsresolver
          image: ishanRegistry.azurecr.io/dns_resolver:v0.0.4
      restartPolicy: Never
  backoffLimit: 4

