apiVersion: batch/v1
kind: Job
metadata:
  name: dnsresolver
spec:
#  successfulJobsHistoryLimit: 0
  ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
        - name: dnsresolver
          image: ishanRegistery.azurecr.io/dns_resolver:v0.0.2
      restartPolicy: Never
  backoffLimit: 4

