apiVersion: v1
kind: ServiceAccount
metadata:
  name: coredns-diagnostics
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
  name: system:coredns-diagnostics
rules:
  - apiGroups:
      - apps
    resources:
      - endpoints
      - services
      - pods
      - namespaces
      - deployments
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
  name: system:coredns-diagnostics
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:coredns-diagnostics
subjects:
  - kind: ServiceAccount
    name: coredns-diagnostics
    namespace: kube-system
